### ISSUE TITLE
Unable to perform any actions on any other realm other than admin

### ISSUE THREAD

**Issue by marcospereirampj** [marcospereirampj/python-keycloak#1]
As KeycloakAdmin class is tied to KeycloakOpenID to perform any action, and instantiation of keycloak_openid object consumes the keycloakadmin attributes, an admin from master realm cannot perform any action in any other realm.

The solution would be to accept separate parameter action_realm_name in KeycloakAdmin class that would be then used as path parameter realm_name instead of the realm_name(master) that is used to retrieve accesstoken from keycloak_openid object.

**Comment by luroden** [comment]
So I ran into a similar problem but found an easy solution:

```
        keycloak_admin = KeycloakAdmin(server_url=server_url,
                               username=username,
                               password=password,
                               realm_name=realm_name,
                               verify=True)
        keycloak_admin.realm_name = managed_realm
```
This would probably break if you needed to renew the token, but I'm using it in short bursts for scripting. Depending on your implementation this may help. I agree though it should be broken out and made a kwarg.

**Comment by marcospereirampj** [comment]
Thanks, @realdavidops.
