### ISSUE TITLE
Documentation on disabling ssl checks

### ISSUE THREAD

**Issue by RubenGarcia** [marcospereirampj/python-keycloak#11]
I have tried disabling ssl checks in order to test the library in a development setting.
In particular, using
https://stackoverflow.com/questions/35875298/python-3-urllib-with-self-signed-certificates
I tried various variations of
ssl._create_default_https_context = ssl._create_unverified_context
at initialization, but I still get the same SSL error:
HTTPSConnectionPool(host='a.b.c.d', port=8443): Max retries exceeded with url: /auth/realms/REALM/.well-known/openid-configuration (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))

Can you add some documentation regarding this?

I have also created an issue at django-keycloak; please coordinate with django-keycloak as appropriate.
https://github.com/Peter-Slump/django-keycloak/issues/21

Thank you.

**Comment by marcospereirampj** [comment]
Hi Ruben.
I think the "django-keycloak" use "python-keycloak-client", not "python-keycloak". Could you check that?

**Comment by RubenGarcia** [comment]
You are right. Sorry.
