### ISSUE TITLE
create_authentication_flow - 400: b'{"error":"unknown_error"}'

### ISSUE THREAD

**Issue by chopmann** [marcospereirampj/python-keycloak#126]
https://github.com/marcospereirampj/python-keycloak/blob/3a45fa5d4e55b4cb3685db6726a819f8972f3d64/keycloak/keycloak_admin.py#L1183

Just like the other `create_XX` methods, this should also use `json.dumps(payload)`.

**Comment by ggallard** [comment]
This was fixed in https://github.com/marcospereirampj/python-keycloak/commit/ab1e2fd5765a04e97d11e7438f54566b4913335a#diff-1f4dc363a2d3b7876c553c0b33fd48a309b58028c4c1c13ade06a6b963f506a4
