### ISSUE TITLE
SUGGESTION: Rename `well_know` to `well_known` + cache

### ISSUE THREAD

**Issue by pierregm** [marcospereirampj/python-keycloak#148]
The current method name makes little sense in english. It'd be nicer to call it `get_well_known`.

Moreover, as the `well_known` endpoint is used several times in the code, why not making it a property ?

```python
class KeycloakOpenID:
    def __init__(...):
        ...
        self._well_known = None

    @property
    def well_known(self):
        if not self._well_known:
            self._well_known = self.get_well_known()
        return self._well_known

```

**Comment by jLebioda** [comment]
Makes a lot of sense, since this typo actually reduces credibility of the project

**Comment by ryshoooo** [comment]
Fixed
