### ISSUE TITLE
Remove forced `self.get_token` or allow override

### ISSUE THREAD

**Issue by svintit** [marcospereirampj/python-keycloak#163]
In my use case, I already have a validated token, I just need to use the token I already have to initialize `KeycloakAdmin` which I can't seem to find a way to do. 

Happy to listen to any suggestions.

**Comment by double-a** [comment]
The initializer does not provide the possibility to override this. For penetration testing I can see that this would make sense, but otherwise ... What's your use case?

**Comment by ryshoooo** [comment]
Agreed with @svintit, I got hit by this enforcement multiple times, mainly in test cases. I actually think that the functionality is already there for this to not be called in the `__init__` method, so this change could really just be deleting that 1 line of code, and everything should work as it usually does. I'll take a look at this the moment we have the Admin fully covered with tests.

**Comment by svintit** [comment]
Closing this as I created a fork of another package and used that instead - https://github.com/svintit/flask-oidc-ext
