### ISSUE TITLE
Updating user `groups` does nothing

### ISSUE THREAD

**Issue by svintit** [marcospereirampj/python-keycloak#164]
```python

new_values = {"enabled": True, "groups": ["custom-group"]}
self._keycloak_admin.update_user(user_id, new_values)
```

Any other value works fine, groups does not work though. 

Everything works fine on user creation, including groups.

**Comment by double-a** [comment]
I think you need to use `groups_users_add()` to add a user to a group.

**Comment by svintit** [comment]
Closing this as I created a fork of another package and used that instead - https://github.com/svintit/flask-oidc-ext

**Comment by tedmdelacruz** [comment]
> I think you need to use `groups_users_add()` to add a user to a group.

I can't find the `groups_users_add` function anywhere in the codebase. Am I missing something?

**Comment by tedmdelacruz** [comment]
Nevermind, it's `group_user_add`
