### ISSUE TITLE
Q: Possibility to change the realm of an KeycloakOpenID and KeycloakAdmin object

### ISSUE THREAD

**Issue by domsie** [marcospereirampj/python-keycloak#171]
Hi, 
is it possible to change the realm of an KeycloakOpenID and KeycloakAdmin object without creating a new object? (using the same server_url etc.)

**Comment by double-a** [comment]
Currently the API does not support this. You would need to get a new token anyway thus the overhead is probably neglectable.

**Comment by ryshoooo** [comment]
Now there are helper methods called `get_current_realm` and `change_current_realm` in the admin client to identify and change realms.
