### ISSUE TITLE
Unable to create/update user's custom attributes 

### ISSUE THREAD

**Issue by ShivCharanSharma** [marcospereirampj/python-keycloak#184]
Hi everyone,

Creating custom attribute for new user using:-
`new_user = keycloak_admin.create_user({"email": "example@example.com",
                    "username": "example@example.com",
                    "enabled": True,
                    "firstName": "Example",
                    "lastName": "Example",
                     "birthdate":"04-01-2000"
                    }) 
 `
 
 OR updating custom attribute for existing user using:-
 
 `response = keycloak_admin.update_user(user_id="user-id-keycloak", 
                                      payload={'birthdate': '14-03-2000'})
`
gives following error:

`
keycloak.exceptions.KeycloakGetError: 400: b'Unrecognized field "birthdate" (class org.keycloak.representations.idm.UserRepresentation), not marked as ignorable'
`

Does I am doing something wrong ?
If it is not already implemented, I will love to help. 

Any suggestion will be highly appreciated.

**Comment by double-a** [comment]
Pushing data into the user attributes needs to be done slightly different as the key is `attributes` and the value must contain the data (which is the key-value pair). 
For create_user() you can add
`"attributes": {"birthdate":'12-01-2021'},`
and for `update_user()` you can use
`payload={ 'attributes':{'birthdate':'14-03-2000'}}`

**Comment by ShivCharanSharma** [comment]
> Pushing data into the user attributes needs to be done slightly different as the key is `attributes` and the value must contain the data (which is the key-value pair).
> For create_user() you can add
> `"attributes": {"birthdate":'12-01-2021'},`
> and for `update_user()` you can use
> `payload={ 'attributes':{'birthdate':'14-03-2000'}}`

Hi,
Thanks for quick reply,
Now I am able to create and update custom attributes.
Thanks for providing the solution. :-)

**Comment by chung1912** [comment]
> Pushing data into the user attributes needs to be done slightly different as the key is `attributes` and the value must contain the data (which is the key-value pair). For create_user() you can add `"attributes": {"birthdate":'12-01-2021'},` and for `update_user()` you can use `payload={ 'attributes':{'birthdate':'14-03-2000'}}`
how to delete custom attribute for existing user？
