### ISSUE TITLE
Add client function

### ISSUE THREAD

**Issue by jumbokun** [marcospereirampj/python-keycloak#191]
Seems it is still not supported to add a new client.
I tried restAPI today and found out that
`
def get_admin_token():
    url = baseurl + 'realms/master/protocol/openid-connect/token'
    params = {
        'client_id': 'admin-cli',
        'grant_type': 'password',
        'username': 'admin',
        'password': 'admin'
    }
    x = requests.post(url, params, verify=False).content.decode('utf-8')
    return ast.literal_eval(x)['access_token']
    # return requests.post(url, params, verify=False).content.decode('utf-8')

def create_client(admin_token):
    url = baseurl + 'admin/realms/master/clients'
    headers = {
        'content-type': 'application/json',
        'Authorization': 'Bearer ' + admin_token
    }

    params = {"clientId": "testclient",
              "id": "100",
              "name": "testclient",
              "enabled": True,
              "redirectUris": ["*"],
              "publicClient": True
              }
    x = requests.post(url, headers=headers, json=params).content.decode('utf-8')
    print(x)`
worked. Please consider adding this to the library.

**Comment by double-a** [comment]
Did you see `keycloak_admin.create_client()`?
E.g. `client = keycloak_admin.create_client({"enabled":True, "clientId":"testclient", "protocol":"openid-connect"}, False)`

**Comment by jumbokun** [comment]
> Did you see `keycloak_admin.create_client()`?

From the released doc, no sir.
https://pypi.org/project/python-keycloak/

**Comment by double-a** [comment]
Yeah... bad that the full api documentation is not included. But if you open up keycloak_admin.py you should find it easily. I believe there was already another issue on that topic.

**Comment by jumbokun** [comment]
Thank you for telling me that. I will go to check keycloak_admin.py.  👍
