### ISSUE TITLE
Way to Impersonate User as you would through the UI, via api

### ISSUE THREAD

**Issue by Alex-Wenner-FHR** [marcospereirampj/python-keycloak#195]
Would love the ability to impersonate a user through the api as you are able to through the front end. It would be much easier if this was a capability!

**Comment by double-a** [comment]
This would be a feature request. 
It seems to be a single endpoint (`POST /{realm}/users/{id}/impersonation`) thus it should not be a big effort. 
What is the use case behind?

**Comment by Alex-Wenner-FHR** [comment]
I have access to get into our application programmatically, which is authenticated by Keycloak, as my own user or service account, etc. However, often I find myself (as admin) impersonating users to go in and access some of their data to perform actions that I cannot do signed into anyone but the user being impersonated. With this said, the fact that I have to impersonate those users, hinders my ability to do those actions programmatically. Rather now I have to do it all through the UI which is extremely inconvenient and slow!
