### ISSUE TITLE
where is the api endpoint for authentication

### ISSUE THREAD

**Issue by Ming-Lyu** [marcospereirampj/python-keycloak#206]
where can i find the function for open authentication, I tried `auth_url`, the server logs:
```
17:06:58,084 WARN  [org.keycloak.services] (default task-2) KC-SERVICES0091: Request is missing scope 'openid' so it's not treated as OIDC, but just pure OAuth2 request.

``` 

the server recognize this request as OAuth2 since it doesn't specify the `scope` parameter, should I custimze this method to include `scope=id` to make the authentication work?

**Comment by double-a** [comment]
Which function are you using?

**Comment by Zerek-Cheng** [comment]
i found the problem and fix it
> https://github.com/marcospereirampj/python-keycloak/pull/353
