### ISSUE TITLE
Stale state causing KeycloakAuthenticationError for admin access? Works on restart of flask application

### ISSUE THREAD

**Issue by RAbraham** [marcospereirampj/python-keycloak#21]
Hi,
I'm using the `KeycloakAdmin` object to access the Admin API. It consistently fails after a few hits giving an `KeycloakAuthenticationError`. On restarting my app, the error goes away only to return after a while. My code is

```python
keycloak_admin_api = KeycloakAdmin(server_url=keycloak_config['keycloak_url'],
                                   username=keycloak_config['keycloak_admin'],
                                   password=keycloak_config['keycloak_password'],
                                   verify=True)
...

 keycloak_admin_api.get_user(user_id)
```
giving the error:

```
...
   owner = keycloak_admin_api.get_user(custom_id)
  File "/Users/rabraham/Documents/dev/fifteenrock/compute/venv/lib/python3.6/site-packages/keycloak/keycloak_admin.py", line 247, in get_user
    return raise_error_from_response(data_raw, KeycloakGetError)
  File "/Users/rabraham/Documents/dev/fifteenrock/compute/venv/lib/python3.6/site-packages/keycloak/exceptions.py", line 102, in raise_error_from_response
    response_body=response.content)
keycloak.exceptions.KeycloakAuthenticationError: 401: b''
```

Note: I'm running this within a flask application with incremental hot loading. I didn't have this problem before if I remember correctly. I'm on `jboss/keycloak:4.1.0.Final` image.

**Comment by marcospereirampj** [comment]
Hi @RAbraham .

When you create an instance of KeycloakAdmin, a token is generated. This token also has an expiration date and is not automatically renewed. Probably the instance creation of KeycloakAdmin is in a place where it runs only at application start.

When you restart your application, a new token will be generated and the issue will not occur until your token expires again.

**Comment by RAbraham** [comment]
Thank you very much for clearing that up. I'm using it in the context of an Flask application. You are right that I load it once when the application starts. Is the recommendation that I create a new instance of `KeycloakAdmin` every time a request is made from the client, in each route for each endpoint? I can do that, no problem, but if there is a design pattern or another way of renewing the token, please let me know.

**Comment by RAbraham** [comment]
Hi @marcospereirampj, 
I tried to refresh the creation of the instance with the following code but it still did not work? I was wondering if you could help me figure it out. 

```python
# First time set in my global init file
keycloak_admin_api = KeycloakAdmin(server_url=keycloak_config['keycloak_url'],
                                   username=keycloak_config['keycloak_admin'],
                                   password=keycloak_config['keycloak_password'],
                                   verify=True)

from threading import Timer
import time

def update_data(interval):
    Timer(interval, update_data, [interval]).start()
    global keycloak_admin_api
    keycloak_admin_api = KeycloakAdmin(server_url=keycloak_config['keycloak_url'],
                                       username=keycloak_config['keycloak_admin'],
                                       password=keycloak_config['keycloak_password'],
                                       verify=True)


update_data(30)
```
