### ISSUE TITLE
Token Generation issue in keycloak v14

### ISSUE THREAD

**Issue by althaf004** [marcospereirampj/python-keycloak#217]
hi,

i was trying to generate token in keycloak latest version(14)

token1 = keycloak_openid.token(username, passwords) 

the same works with previous version(11).

please help to sort this issue.

**Comment by double-a** [comment]
Could not find any issue... Any further debug info?

**Comment by althaf004** [comment]
created a client - store_local

made the access type confidential (so that the credentials shows up with client_secret).
made no other changes.


![image](https://user-images.githubusercontent.com/83403907/127430499-4f974405-9645-4750-9d4c-be25f9cafab1.png)


followed by a function:

     keycloak_prov = plpy.execute("select * from keycloak_config")
     keycloak_admin = KeycloakAdmin(server_url=str(keycloak_prov[0]["api_base_url"]), username=str(keycloak_prov[0]["admin_username"]),password=str(keycloak_prov[0]["admin_password"]),  realm_name=str(keycloak_prov[0]["master_realm_name"]), verify=True)   
 
     keycloak_admin.realm_name = keycloak_prov[0]["user_realm_name"] 
     client_id = keycloak_admin.get_client_id(client_name)
     response =keycloak_admin.get_client_secrets(client_id)        
     client_secret_key = response['value']

     keycloak_openid = KeycloakOpenID(server_url=str(keycloak_prov[0]["api_base_url"]), client_id=client_id,realm_name=str(keycloak_prov[0]["user_realm_name"]),client_secret_key=client_secret_key)        
     token = keycloak_openid.token(username, passwords)   


but the response which i get from this function is : with client_name as "store_local"



KeycloakGetError(b'{"error":"invalid_client","error_description":"Invalid client credentials"}',)


but with same configurations other calls are working well for this client. is there any settings which im missing

**Comment by althaf004** [comment]
found out the error:

response =keycloak_admin.get_client_secrets(client_id) 

is suppossed to be 

response =keycloak_admin.get_client_secrets(client_name)
