### ISSUE TITLE
Mismatch in GroupRepresentation and implementation

### ISSUE THREAD

**Issue by siddiqskm** [marcospereirampj/python-keycloak#23]
In reference to the code per permalink: https://github.com/marcospereirampj/python-keycloak/blob/99f69dd37efc59fa9bc471cb9b2ee1137767dc51/keycloak/keycloak_admin.py#L515 - I see the link referenced to in the docstring is invalid and not reachable now.
Hence, docstring's need to be updated per support of the API's.

Now, In the keycloak documentation for group representation: https://www.keycloak.org/docs-api/5.0/rest-api/index.html#_grouprepresentation I see both Name and Path are optional but the implementation mandates both name and path in create_group. Is this expected?

**Comment by marcospereirampj** [comment]
Hi @siddiqskm.

No. It is a mistake. Just like the code snippet (I think):
`
        if name is None and path is not None:
            path="/" + name
`

I'll to fix. Thanks!

**Comment by marcospereirampj** [comment]
Release 0.17.5.
