### ISSUE TITLE
Generating single-use action-tokens not possible?

### ISSUE THREAD

**Issue by cnadolny2s** [marcospereirampj/python-keycloak#230]
When I execute `send_update_account()`, it will trigger Keycloak to send an email with a link containing an action-token. I would like to set this link to be used only once (single-use). The function does not provide this feature and I could not find any other hints on how to do that. The `lifespan` param is not what I need here.

When I init a password reset in Keycloak itself, Keycloak generates such a link, where the link can be used only once and is immediatelly invalidated after that.

Keycloak does mention this feature here at point 5:
https://github.com/keycloak/keycloak-documentation/blob/master/server_development/topics/action-token-spi.adoc#action-token-processing

Btw, the docs are mentioning `nonce` to create a unique usage and the generated action-token contains it but the link is still usable multiple times.

Does this library provide a way to generate links with such action-tokens?

**Comment by double-a** [comment]
What do you mean with link usable?
The documentation says 'If the token is set to single-use, once the authentication flow finishes, the action token is invalidated.' 
Thus the link is not invalidated but the token is not usable any more once you finish the authentication flow. Did you do that?

**Comment by cnadolny2s** [comment]
I meant the action token and its encoded required actions. We already figured out, that the action token behind the link gets invalidated, when ALL required actions are fullfilled by the user. If one is not, all keycloak screens (pw reset, terms and conditions, etc.) are shown again.
I'm closing this issues since the behavior seems to be keycloak only related.
