### ISSUE TITLE
MFA for KeycloakAdmin

### ISSUE THREAD

**Issue by JohannesRuc** [marcospereirampj/python-keycloak#257]
Hello everybody,

it would be great if the library could support MFA for admin accounts (_KeycloakAdmin_).

Regular users may use a second factor like TOTP as follows:

> from keycloak import KeycloakOpenID
> keycloak_openid = KeycloakOpenID(server_url="http://localhost:8080/auth/",
>                     client_id="example_client",
>                     realm_name="example_realm",
>                     client_secret_key="secret")
> token = keycloak_openid.token("user", "password", totp="012345")

This is currently not possible for the admins in the master realm (_KeycloakAdmin_), since there is no way to pass a TOTP value due to the hard coded invocation of _self.keycloak_openid.token()_ in _get_token(self)_:

> self.keycloak_openid.token(self.username, self.password, grant_type=grant_type)

However, admin accounts have particularly high protection needs. It would be a shame if someone had to either pass on using MFA for administrative accounts or pass on using _python-keycloak_.

My suggestion would be to extend the existing TOTP mechanism to _KeycloakAdmin_ as outlined below.

Have an additional parameter for the constructor of _KeycloakAdmin_, so it can be instantiated as follows:

> from keycloak import KeycloakAdmin
> keycloak_admin = KeycloakAdmin(server_url="http://localhost:8080/auth/",
>                                username='example-admin',
>                                password='secret',
>                                realm_name="master",
>                                user_realm_name="only_if_other_realm_than_master",
>                                client_secret_key="client-secret",
>                                verify=True,
>                                totp=123456)

Extend _KeycloakAdmin_ as follows:

> diff -u ./env/lib/python3.8/site-packages/keycloak/keycloak_admin.py.orig ./env/lib/python3.8/site-packages/keycloak/keycloak_admin.patch.py
> [...]
> @@ -67,9 +67,10 @@
>      _token = None
>      _custom_headers = None
>      _user_realm_name = None
> \+    _totp = None
> def __init__(self, server_url, username=None, password=None, realm_name='master', client_id='admin-cli', verify=True,
> \-                 client_secret_key=None, custom_headers=None, user_realm_name=None, auto_refresh_token=None):
> \+                 client_secret_key=None, custom_headers=None, user_realm_name=None, auto_refresh_token=None, totp=None):
> @@ -82,6 +83,7 @@
>          :param custom_headers: dict of custom header to pass to each HTML request
>          :param user_realm_name: The realm name of the user, if different from realm_name
>          :param auto_refresh_token: list of methods that allows automatic token refresh. ex: ['get', 'put', 'post', 'delete']
> \+        :param totp: Time based OTP for admin login
>          """
>          self.server_url = server_url
>          self.username = username
> @@ -93,6 +95,7 @@
>          self.auto_refresh_token = auto_refresh_token or []
>          self.user_realm_name = user_realm_name
>          self.custom_headers = custom_headers
> \+        self.totp = totp
> self.get_token()
> @@ -189,6 +192,14 @@
>      def custom_headers(self, value):
>          self._custom_headers = value
>  
> \+    @property
> \+    def totp(self):
> \+        return self._totp
> \+
> \+    @totp.setter
> \+    def totp(self, value):
> \+        self._totp = value
> \+
>      @auto_refresh_token.setter
>      def auto_refresh_token(self, value):
>          allowed_methods = {'get', 'post', 'put', 'delete'}
> @@ -1885,7 +1923,7 @@
>              if self.user_realm_name:
>                  self.realm_name = self.user_realm_name
>  
> \-        self._token = self.keycloak_openid.token(self.username, self.password, grant_type=grant_type)
> \+        self._token = self.keycloak_openid.token(self.username, self.password, grant_type=grant_type, totp=self.totp)

I tested this patch and it works fine. Since _totp=None_ lets the parameter default to being unset, no additional logical branching is required, only an additional property and getter/setter functions.

Hence, TOTP support can be achieved with minimal effort. It would be great if you could consider my suggestion :)

Thank you and best regards
Johannes

**Comment by asyd** [comment]
Hi, any reason this is not merged? Do you expected a PR maybe? 

Cheers

**Comment by ryshoooo** [comment]
This should be now available since v0.28.0
