### ISSUE TITLE
Where do I begin?

### ISSUE THREAD

**Issue by davsumgdit** [marcospereirampj/python-keycloak#259]
1. Can't use client credentials from a sub realm. Only from the master realm.
2. Cannot do anything when using client credentials. I have to use password grant_type to with access type public to do anything... create_user, users_count, etc. Any attempt to do anything with client credentials returns an unknown_error message. I have access type set to confidentials and service accounts enabled.

I need to perform actions on a sub realm and want to use admin-cli client credentials. Is this possible with this module?

**Comment by luismarqu3s** [comment]
from what I saw, you are able to work above client level only. The library will generate you a token based on your client secret.

I'm using requests to reach keycloak rest api and generate a token based on admin-cli

**Comment by davsumgdit** [comment]
I discovered the cause of the issues I was seeing. Permissions for the client authentication user had to be adjusted. Granting them admin role under the client -> Service Account Roles screen.
