### ISSUE TITLE
Bad token when initiating connection to Keycloak

### ISSUE THREAD

**Issue by babastienne** [marcospereirampj/python-keycloak#27]
During the first phase of connection with Keycloak, le token generated isn't working. It is a small token who generate a 403 error (forbidden) when trying to use to make a request.

**Example of the error :**

![image](https://user-images.githubusercontent.com/16348048/65440206-aa603280-de28-11e9-901f-21cf6ccd3f9b.png)

When using the generated token (in Postman for example), we get the following error : 
![image](https://user-images.githubusercontent.com/16348048/65440298-ccf24b80-de28-11e9-96ac-813ba4fc44d7.png)

**Origin of the problem :**

In the `__init__` function of the `KeycloakAdmin` class, the following actions are executed :

- Creation of a connexion with OpenIdConnect
- Asking for a token
- Creation of a connection with the previously generated token

![image](https://user-images.githubusercontent.com/16348048/65439478-818b6d80-de27-11e9-835b-0a3c1b2276a6.png)

When debug, I noticed that the token fetched at this moment is the non working token.
However, if I reproduce the same steps after the initialization of the `KeycloakAdmin` class the newly generated token is working just fine : 

![image](https://user-images.githubusercontent.com/16348048/65440415-fc08bd00-de28-11e9-91ec-5dff585c5f93.png)

![image](https://user-images.githubusercontent.com/16348048/65440497-1b9fe580-de29-11e9-99d7-821dfb93fbe8.png)

**Temporary solution :**

For now I'm working with this dirty solution (and it works fine) but it's definitely not the right way to do it. Any advice on a better way to avoid the problem ? Is it a bug inherit to this module ?

![image](https://user-images.githubusercontent.com/16348048/65439918-3cb40680-de28-11e9-9c4f-2f357dd25d31.png)

**Comment by gt-novelt** [comment]
You are switching from **client_credentials** to **password** _grant_type_. 

If you do not want to use _client_credentials_, initialize _KeycloakAdmin_ with `client_secret_key=None`.
https://github.com/marcospereirampj/python-keycloak/blob/f8b35aabb4475c5533436a2be29cba0c2646f948/keycloak/keycloak_admin.py#L68-L70

**Comment by babastienne** [comment]
Yes, I saw that already. The thing is :
- when I don't provide any _client_secret_key_ I've got the following error (which is completely normal) : 
`400: b'{"error":"unauthorized_client","error_description":"Client secret not provided in request"}'`

- my application worked before when I was initializing the KeycloakAdmin by giving the _client_secret_key_ (with the code below) : 
![image](https://user-images.githubusercontent.com/16348048/65499069-518ea980-debd-11e9-920a-fb697ab42486.png)

Furthermore, the strange behaviour with the code in the screen above is that I get a token but the token isn't working. Few weeks ago I had a working token with the same code. That's why at the beginning I thought it was a Keyclaok configuration problem but I restored my initial configuration (the one who was working already) and the same problem happened.

**Comment by gt-novelt** [comment]
I agree with your first intuition. I don't think it is a python-keycloak issue. Looks like a Keycloak configuration issue to me.

Check if the client you are authenticating with has **Authorization** enabled. Have a look in that direction. I suspect you have a rule that denies your client but allows your user.

Here is some [documentation](https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.2/html/authorization_services_guide/getting_started_overview#getting_started_hello_world_enabling_authz_services) from redhat that could be of some use.

*edit:* check all clients actually.

**Comment by babastienne** [comment]
I looked at the authorization tab in the beginning but maybe not enough. Anyway, thanks a lot for your help. Since it is probably not a python-keycloak problem I'm closing this issue but I will investigate the documentation you sent me in order find a solution in my configuration.

**Comment by Allan-Nava** [comment]
> I looked at the authorization tab in the beginning but maybe not enough. Anyway, thanks a lot for your help. Since it is probably not a python-keycloak problem I'm closing this issue but I will investigate the documentation you sent me in order find a solution in my configuration.

how do u fix?
