### ISSUE TITLE
0.27 seems to break get_group_by_path() always returns a keyerror

### ISSUE THREAD

**Issue by joelcomp1** [marcospereirampj/python-keycloak#270]
we just upgraded to 0.27 from 0.26.1 and ow our get_group_by_path calls no longer work we always get:
keycloak_admin.get_group_by_path(path="group")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/keycloak/keycloak_admin.py", line 790, in get_group_by_path
    if group['path'] == path:
KeyError: 'path'

same call worked fine on 0.26.1

**Comment by samdammers** [comment]
Duplicate of https://github.com/marcospereirampj/python-keycloak/issues/268

**Comment by ryshoooo** [comment]
This issue should be solved now with the latest release https://github.com/marcospereirampj/python-keycloak/releases/tag/0.27.1
