### ISSUE TITLE
KeycloakAdmin expired access_token

### ISSUE THREAD

**Issue by gt-novelt** [marcospereirampj/python-keycloak#28]
When _KeycloakAdmin_'s _access_token_ expires, call to the api will return _KeylcoakAuthenticationError_.

There is no easy way to refresh the token. Although you have _refresh_token_, the _KeycloakOpenID_ instance used to get the _access_token_ is not persisted. And thus it's _refresh_token_ method is not available.

It would be nice to have a kind of "auto_refresh" feature that would retry the request with a refreshed token whenever the _access_token_ expires.

**Comment by gt-novelt** [comment]
related issue: #21

**Comment by RAbraham** [comment]
@gt-novelt Do you have a workaround for this issue right now? I tried [this](https://github.com/marcospereirampj/python-keycloak/issues/21#issuecomment-537739461) and it did not work for me.

**Comment by gt-novelt** [comment]
@RAbraham yes I did fix it. Still testing it before I propose a PR.

Have a look at: 
https://github.com/gt-novelt/python-keycloak
commits: 7931608 & d72340d

Basically it will refresh the token with its refresh_token or reask for a new one if that fails. It will automatically retry the request.
This behaviour might not suit every cases, that is why I added a _auto_refresh_token_ argument to fine tune which methods (_GET_, _POST_, _PUT_, _DELETE_) you want this behaviour to occur.

**Comment by RAbraham** [comment]
@gt-novelt That's wonderful. Hoping it gets accepted. In the interim, my applications are failing :(. Do you know of any workarounds I can do now to make it work while I wait for your PR to be accepted?

**Comment by gt-novelt** [comment]
You can create a new instance of _KeycloakAdmin_ each time you want to perform an admin action.

Although you lose the benefit of both the opened request.session and refresh_token, I suppose this is the way it is meant to be used.

**Comment by RAbraham** [comment]
Thanks, I did try creating a new instance (shown below) unless I'm doing something wrong. I also do it at at `@app.before_request` in `flask`.

```python
# First time set in my global init file
keycloak_admin_api = KeycloakAdmin(server_url=keycloak_config['keycloak_url'],
                                   username=keycloak_config['keycloak_admin'],
                                   password=keycloak_config['keycloak_password'],
                                   verify=True)

from threading import Timer
import time

def update_data(interval):
    Timer(interval, update_data, [interval]).start()
    global keycloak_admin_api
    keycloak_admin_api = KeycloakAdmin(server_url=keycloak_config['keycloak_url'],
                                       username=keycloak_config['keycloak_admin'],
                                       password=keycloak_config['keycloak_password'],
                                       verify=True)


update_data(30)

```

If it's wrong, is there any other way?

**Comment by RAbraham** [comment]
@gt-novelt I copied your repo into my project and it worked :). Thanks, hope it gets accepted.

**Comment by lucasln** [comment]
Hello, It would be great to have this feature in the next version. I'm creating a new admin instance for each request in my application, but it takes more than 300ms by connection. So, this feature will improve my application performances.
