### ISSUE TITLE
License headers in test files indicate LGPL instead of MIT 

### ISSUE THREAD

**Issue by Daniel-Roennpagel** [marcospereirampj/python-keycloak#283]
Hello,

the test file https://github.com/marcospereirampj/python-keycloak/blob/master/keycloak/tests/test_connection.py contains a LGPL license text. 
Is this intentional?

This is related to issue https://github.com/marcospereirampj/python-keycloak/issues/30. Some files with LGPL notice where transformed to MIT. Can this be done for test files too?

Best regards
Daniel

**Comment by ryshoooo** [comment]
The test files were removed. The new test files have no license headers for now :) Thanks for the issue report!
