### ISSUE TITLE
def get_groups does not work as expected 

### ISSUE THREAD

**Issue by ziaudin** [marcospereirampj/python-keycloak#285]
in def get_groups(self, query=None):

url = URL_ADMIN_USERS.format(**params_path)

should be replaced with:

url = URL_ADMIN_GROUPS.format(**params_path)

https://github.com/marcospereirampj/python-keycloak/blob/master/keycloak/keycloak_admin.py#L708

**Comment by andreiaciobanitei** [comment]
Same issue. It retrieves users instead of groups.

**Comment by FAUSheppy** [comment]
Already a PR for that: https://github.com/marcospereirampj/python-keycloak/pull/267

**Comment by ryshoooo** [comment]
This issue should be solved now with the latest release https://github.com/marcospereirampj/python-keycloak/releases/tag/0.27.1
