### ISSUE TITLE
The problem is in the new version of the library for getting groups via KeycloakAdmin

### ISSUE THREAD

**Issue by stalexsm** [marcospereirampj/python-keycloak#292]
В новой версии библиотеки (0.27.0) есть проблема с получением групп через KeycloakAdmin... Вместо URL_ADMIN_GROUPS. используется URL_ADMIN_USERS....
<img width="627" alt="Снимок экрана 2022-04-05 в 10 46 21" src="https://user-images.githubusercontent.com/10753523/161775155-3e62a50f-c4b4-4412-8b0b-795227eadd5c.png">

**Comment by stalexsm** [comment]
In the new version of the library (0.27.0) there is a problem with getting groups via KeycloakAdmin... Instead of URL_ADMIN_GROUPS. URL_ADMIN_USERS is used....

**Comment by ryshoooo** [comment]
This issue should be solved now with the latest release https://github.com/marcospereirampj/python-keycloak/releases/tag/0.27.1
