### ISSUE TITLE
get_groups() return user objects in 0.27.0 release 

### ISSUE THREAD

**Issue by hafeez84** [marcospereirampj/python-keycloak#295]
get_groups() return user objects because of the following line 

keycloak_admin.py
708 -> url = URL_ADMIN_USERS.format(**params_path)

**Comment by RSWilli** [comment]
can confirm, you can fix it by changing line 708 to:

```python
url = URL_ADMIN_GROUPS.format(**params_path)
```

**Comment by Eric-Fontana-Indico** [comment]
Yes, this is broken.

**Comment by robin-thoni** [comment]
Just hit this issue 5 minutes ago. Fix was release 1 minute ago. Awesome timing.

**Comment by ryshoooo** [comment]
This issue should be solved now with the latest release https://github.com/marcospereirampj/python-keycloak/releases/tag/0.27.1
