### ISSUE TITLE
License headers in some files indicate LGPL instead of MIT

### ISSUE THREAD

**Issue by bs-jokri** [marcospereirampj/python-keycloak#30]
Hi,

I found your library and it is quite handy. Thanks for providing that!

After cursory looking through the code base I found two files [1,2] that have a LGPL instead of an MIT header. Is this intended? If so what is the reason behind that? If there is no special reason for having this, would it be possible to adjust the headers to the project license (MIT)?

The reason I am asking is that we would like to use your library for our project [3], which is EPL 2.0 licensed and would have a clash in the licensing conditions.

[1] https://github.com/marcospereirampj/python-keycloak/blob/master/keycloak/__init__.py
[2] https://github.com/marcospereirampj/python-keycloak/blob/master/keycloak/authorization/__init__.py
[3] https://www.eclipse.org/kuksa/

**Comment by marcospereirampj** [comment]
Hello @bs-jokri .

It was not intentional. I will change and release a new patch.

Thanks for the trouble!

**Comment by marcospereirampj** [comment]
@bs-jokri Version 0.17.6.

**Comment by bs-jokri** [comment]
@marcospereirampj great! Thank you very much for this adjustment.
