### ISSUE TITLE
KeycloakAdmin making requests on another realm

### ISSUE THREAD

**Issue by ghost** [marcospereirampj/python-keycloak#320]
I am using keycloak in combination with Eclipse Che, which means Keycloak is provisioned with two realms: master and che. The master realm contains the admin user that can be used to create a KeycloakAdmin, but I want to use it to create a user in the che realm. However everything I see in [the docs](https://python-keycloak.readthedocs.io) seems to implicitly reference the realm that the KeycloakAdmin object was created with, with no apparent way to change it. eg. `get_users` just returns the users from the master realm and doesn't seem to have any relevant parameters.

If I use `raw_get`, I can fetch the users from the che realm, but surely there's a way to do it with the library's main API right?

**Comment by ryshoooo** [comment]
Hi @yujiri8 

Change of realm is one of the issues I'd like to solve in a near future. It is not impossible with the latest version, it's just not intuitive nor documented well enough.

You can simply switch realms by setting the `realm_name` attribute of the admin object. Example:

```python
admin = KeycloakAdmin(...)

# Get user in master realm
admin.get_users()

# Change realm to 'che'
admin.realm_name = "che"

# Get users in realm che
admin.get_users()
```

I do wish to introduce a simple classish-like method that is going to return an admin instance with the wanted realm. It's not hard to do, just currently prioritizing test coverage of existing methods. Hope this helps!

**Comment by ghost** [comment]
Thank you! That works for me.
