### ISSUE TITLE
reason for urllib3 dependency

### ISSUE THREAD

**Issue by fcollonval** [marcospereirampj/python-keycloak#336]
I'm maintaining the [conda recipe](https://github.com/conda-forge/python-keycloak-feedstock) for this package and realize urllib3 is supposed to be a dependency there: https://github.com/marcospereirampj/python-keycloak/blob/176b3cde4115f18c5ae53851e51870097524cb3f/requirements.txt#L3

But it is not used explicitly in the code. So I'm wondering why is it listed in the requirements?

**Comment by ryshoooo** [comment]
It's based on this PR https://github.com/marcospereirampj/python-keycloak/pull/301, we're using `allowed_methods` in https://github.com/marcospereirampj/python-keycloak/blob/master/src/keycloak/connection.py#L61 which is only supported for `urllib3>=1.26.0`. I could be wrong in the assessment though and it might not be actually explicitly needed.

**Comment by fcollonval** [comment]
Thanks for the feedback. I'll update the dependency in the conda forge package too.
