### ISSUE TITLE
Invalid code on Authentication using code

### ISSUE THREAD

**Issue by althaf004** [marcospereirampj/python-keycloak#339]
Token generation using code was working fine till last week, all of a sudden the code stopped working, with error message:
`"{\"error\": \"invalid_grant\", \"error_description\": \"Code not valid\"}"`

token was generated using
` token = keycloak_openid.token(code=access_code, grant_type=["authorization_code"],redirect_uri=redirecturl) `

Please let me know if it is to do with latest keycloak_sdk change or not.

**Comment by ryshoooo** [comment]
Very unlikely as this part of the codebase hasn't been touched for a long time. But do you have a MRE (minimum reproducible example)?
