### ISSUE TITLE
create hierarchical user groups

### ISSUE THREAD

**Issue by tkzkno** [marcospereirampj/python-keycloak#341]
I want to create hierarchical user groups using python-keycloak. 
A hierarchical user group would look something like this.

![image](https://user-images.githubusercontent.com/70999215/173494459-409b1d9c-d056-421b-a51a-f041aa470ab0.png)

But about creating user groups, I could only find this.
`# Create new group #`
`group = keycloak_admin.create_group({"name": "Example Group"})`

What should I do?

**Comment by ryshoooo** [comment]
Hi @tkzkno 

You can pretty easily create subgroups by specifying the `parent` parameter in the `create_group` method. So for your case it'd be

```python
top_group_id = keycloak_admin.create_group(payload={"name": "admin"})
middle_group_id = keycloak_admin.create_group(payload={"name": "test1"}, parent=top_group_id)
bottom_group_id_1 = keycloak_admin.create_group(payload={"name": "test2"}, parent=middle_group_id)
bottom_group_id_2 = keycloak_admin.create_group(payload={"name": "test3"}, parent=middle_group_id)
```

**Comment by tkzkno** [comment]
Thank you for your comment @ryshoooo 

That works well !

**Comment by tkzkno** [comment]
@ryshoooo  Thank you for your comment.

```
top_group_id = keycloak_admin.create_group(payload={"name": "admin"})
middle_group_id = keycloak_admin.create_group(payload={"name": "test1"}, parent=top_group_id)
```

But this error happens.
```
keycloak.exceptions.KeycloakGetError: 404: b'{"error":"Could not find group by id"}'
```

```
top_group_id = keycloak_admin.create_group(payload={"name": "admin"})
print(top_group_id) # b''
```

Perhaps the group ID is not being output by create_group.

**Comment by ryshoooo** [comment]
Do you have the latest version of python-keycloak installed? The change where create_group returns the group id was fairly recent.

**Comment by tkzkno** [comment]
thank you @ryshoooo 

after runnning `pip3 install -U python-keycloak`
that works very well
