### ISSUE TITLE
Master realm (admin service account/admin-cli) not able to manage users in new Realm

### ISSUE THREAD

**Issue by deba1234** [marcospereirampj/python-keycloak#344]
Hi guys,
first of all this is very useful library for working with Keycloak, thanks for your support.
I have one specific question which I am not sure is issue or i not understand and utilise some python-keycloak methods correctly.

Short background, i want to create some python CLI tool for managing Keycloak realms with the following functionalities: 
- create new realm (for example my-demo-realm) with predefined settings - DONE (with admin-cli and master),
- create/delete users from realm and also assign them to different roles
- add roles to realm 

My issue is that i am not able create new user inside specific realm ( in this case : my-demo-realm)

Option 1: Utilise  master realm admin-cli to create new realm and user inside

    keycloak_admin = KeycloakAdmin(server_url="http://localhost:8080/",
                                   username='admin',
                                   password='admin',
                                   realm_name="master",
                                   verify=True)
    # WORKS
    # my-demo-realm params are stored in generated_realm_data var
    response = keycloak_admin.create_realm(payload=generated_realm_data, skip_exists=False)

    # ADD user to my-demo-realm
    keycloak_admin = KeycloakAdmin(server_url="http://localhost:8080/",
                                   username='admin',
                                   password='admin',
                                   realm_name="master",
                                   user_realm_name='my-demo-realm',
                                   verify=True)

    new_user = keycloak_admin.create_user({"email": "example3@example.com",
                                           "username": "example3@example.com",
                                           "enabled": True,
                                           "firstName": "Example3",
                                           "lastName": "Example3",
                                           "credentials": [{"value": "secret", "type": "password"}]})

Option 2:
Also i tried to create Service account client under master realm (and assign it to admin role) like this 

    keycloak_admin = KeycloakAdmin(server_url="http://localhost:8080/",
                                   client_id=SERVICE_ACCOUNT_CLIENT_ID,
                                   client_secret_key=SERVICE_ACCOUNT_CLIENT_SECRET,
                                   realm_name='master',
                                   user_realm_name='my-demo-realm',
                                   verify=True)

And when i tried to execute i get this error:
ERROR: keycloak.exceptions.KeycloakGetError: 400: b'{"error":"invalid_client","error_description":"Invalid client credentials"}'

My expectation in both approaches is that this will get access token from master using admin-cli (password) or service account (client_credentials) settings to get admin access token and then it will utilise admin_access token in header towards defined user_realm_name (see CURL example)

With CURL (pasted from Makefile where TOKEN_1 is access token get from form admin-cli client and )

create_realm_user:
	@curl -s -X POST \
	-H "Authorization: Bearer ${TOKEN_1}" \
	-H "Content-Type: application/json" \
	-d @templates/new-user.json \
	"http://localhost:8080/admin/realms/my-demo-realm/users"

Not sure what i am doing wrong, any comment will be more than welcome. Thanks

**Comment by deba1234** [comment]
After some investigation i manage to find solution, putting here example just if someone will need it in the future

    keycloak_admin = KeycloakAdmin(server_url="http://localhost:8080/",
                                   username='admin',
                                   password='admin',
                                   realm_name="master",
                                   verify=True)

    # Set realm name which we want to manage
    keycloak_admin.realm_name = 'my-demo-realm'

    # Create user inside
    user_id = keycloak_admin.create_user(payload={
        "email": "demo1@example.com",
        "username": "demo1",
        "enabled": True,
    })

In this case admin access token is created and used for manage custom realm

**Comment by ryshoooo** [comment]
Hi @deba1234 

You are not the first one struggling a bit with realms and how to set the admin client to create/update/delete resources in a specific realm (f.e. https://github.com/marcospereirampj/python-keycloak/issues/320). The last example you gave is the one I tend to recommend the most, but I also have a plan to make switching realms a bit easier and more intuitive in the future.

I have no doubts that there will be someone else in the future needing this example :) If you feel like it, feel free to add this example to the README.md. I'll approve and merge it pretty quickly.
