### ISSUE TITLE
Add functions for roles to keycloak_admin

### ISSUE THREAD

**Issue by LucaPaganin** [marcospereirampj/python-keycloak#347]
I suggest to add these missing functions to keycloak admin

```
    def get_composite_client_roles_of_group(self, client_id, group_id):
        params_path = {"realm-name": self.realm_name, "id": group_id, "client-id": client_id}
        data_raw = self.raw_get(URL_ADMIN_GROUPS_CLIENT_ROLES_COMPOSITE.format(**params_path))
        return raise_error_from_response(data_raw, KeycloakGetError)
    
    def get_role_client_level_children(self, client_id, role_id):
        params_path = {"realm-name": self.realm_name, "role-id": role_id, "clientUuid": client_id}
        data_raw = self.raw_get(URL_ADMIN_CLIENT_ROLE_CHILDREN.format(**params_path))
        return raise_error_from_response(data_raw, KeycloakGetError)
```

Along with these definitions for the missing URLs

```
URL_ADMIN_GROUPS_CLIENT_ROLES_COMPOSITE = URL_ADMIN_GROUPS_CLIENT_ROLES+"/composite"
URL_ADMIN_CLIENT_ROLE_CHILDREN = "admin/realms/{realm-name}/roles-by-id/{role-id}/composites/clients/{clientUuid}"
```

**Comment by LucaPaganin** [comment]
Any news on this issue? I opened it 24 days and I haven't got an answer yet. I also provided the code... Should I open a pull request?

**Comment by ryshoooo** [comment]
> Any news on this issue? I opened it 24 days and I haven't got an answer yet. I also provided the code... Should I open a pull request?

Hi @LucaPaganin 

Sorry, but I didn't see any question, so didn't provide any answer ;) I'll look into this when I find some free dev time, but looks like you have what you want already coded? In that case, if you wish to have this faster inside of the library, you can always contribute yourself ;)

**Comment by LucaPaganin** [comment]
HI @ryshoooo ,

I've just opened a pull request with the modifications that I have done so far :)
