### ISSUE TITLE
Conflicting dependency management

### ISSUE THREAD

**Issue by chumaumenze** [marcospereirampj/python-keycloak#349]
There are multiple tools for dependency and package management setup. Pipenv, setup tools, pep517/8, requirements file.

These are confusing. Can there be just one in place? A single source of truth.

Personally, I prefer PEP517 and I use poetry for it. It covers everything including locking 🔑.

**Comment by ryshoooo** [comment]
SGTM, as long as `tox` keeps working the same way :)

**Comment by chumaumenze** [comment]
@ryshoooo I opened a PR #350  on this. Can you take a look?
