### ISSUE TITLE
`URL_AUTH` pattern has space at the end

### ISSUE THREAD

**Issue by idanambar** [marcospereirampj/python-keycloak#359]
for some reason `URL_AUTH` has a space at the end.
https://github.com/marcospereirampj/python-keycloak/blob/fb8663e0ac2656d1b5f62cb28eef5c291f1cfd08/src/keycloak/urls_patterns.py#L35
When we pass `state` to [`auth_url`](https://github.com/marcospereirampj/python-keycloak/blob/fb8663e0ac2656d1b5f62cb28eef5c291f1cfd08/src/keycloak/keycloak_openid.py#L187), this space is added at the end and when we get it back we fail to decode it.

Is there a reason that space is there?

**Comment by ryshoooo** [comment]
Hmm no this seems to be a bug, shouldn't be any space at the end :)
