### ISSUE TITLE
realmRoles doesn't work

### ISSUE THREAD

**Issue by mtung-metromile** [marcospereirampj/python-keycloak#37]
I tried to in the admin client create a new user with role "admin". Client creates user but does not assign the realm role at all.

**Comment by gt-novelt** [comment]
As a workarround you can use `assign_realm_roles`
https://github.com/marcospereirampj/python-keycloak/blob/10e54287d96d59762b771f7ec9a2f3df6a9538a9/keycloak/keycloak_admin.py#L830
