### ISSUE TITLE
Empty request in exceptions.py

### ISSUE THREAD

**Issue by Kirralex** [marcospereirampj/python-keycloak#386]
Hello!
I'm working with dash and use this library. In new keycloak version (20.0.1) I noticed that after authorization dash is sends an empty request `b''` with code 403.
I add in function `raise_error_from_response`  in the `exceptions.py` code:
`if response.content == b'':
 return`
It works, but I would like to understand why this is happening and whether it could be a problem on the part of python-keycloak

Sorry if I didn't formulate the problem very clearly, I'm more an analyst, not a developer :)

**Comment by ryshoooo** [comment]
It is, right now python-keycloak is not up-to-date with Keycloak 20+, only with Keycloak 19. I'm currently still working on the Keycloak 20 integration.

**Comment by Kirralex** [comment]
Thanks for the answer!
