### ISSUE TITLE
userinfo api for keycloak quarkus v 20.0.1

### ISSUE THREAD

**Issue by althaf004** [marcospereirampj/python-keycloak#389]
We where using keycloak quarkus 19.0.2 and had to upgrade to 20.0.1. Userinfo api was working fine till then. After the migration, api started to respond as `403 : b ''`. Below is the function which we are using for fetching userinfo.

```
$function$
      import json
      from keycloak import KeycloakOpenID
      from keycloak import KeycloakAdmin
      try:         
        keycloak_admin = KeycloakAdmin(server_url=api_base_url,
                                         username=admin_username,
                                         password=admin_password,
                                         realm_name=master_realm,                                     
                                         verify=True)    
        keycloak_admin.realm_name = user_realm_name
        client_id = keycloak_admin.get_client_id(client_name)
        response =keycloak_admin.get_client_secrets(client_id)
        client_secret_key = response['value']	
        keycloak_openid = KeycloakOpenID(server_url=api_base_url,
                          client_id=client_id,
                          realm_name=user_realm_name,
                          client_secret_key=client_secret_key)        
        userinfo = keycloak_openid.userinfo(access_token)	
        return json.dumps(userinfo);                 
      except Exception as error:
        return json.dumps(json.loads(error.args[0]))
      $function$
```
we had to downgrade keycloak to previous version for our application to start working. Requesting to please fix this.

Thanks

**Comment by ryshoooo** [comment]
Hi @althaf004 

yes I'm very well aware of this. I'm still working on the fix, but unfortunately, I'm also quite busy with my real job :) Anybody is welcome to contribute

**Comment by mitchell-gottlieb** [comment]
Hi @althaf004 @ryshoooo,

When switching to Keycloak v 20.0.1, I ran into the same issue you're seeing. It looks like the responsibility is on the requester to include the scope [(see here).](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) I was able to get it working again using python-keycloak v 2.6.0 and Keycloak v 20.0.1 (see solution below)

```
# Previous Solution (no longer working)
token = keycloak_openid.token("user", "password")

# New Solution (working)
token = keycloak_openid.token("user", "password", scope="openid")

userinfo = keycloak_openid.userinfo(token["access_token"])
```

If you want to update python-keycloak, feel free.  I just wanted to put this out for everyone to see. Thanks.

**Comment by ryshoooo** [comment]
> mitchell

Thank you so much @mitchell-gottlieb for looking into this :) I'll update the package to include `scope="openid"` as the default value, so we get the "normal" behavior for `.token("user", "password")` as before :)
