### ISSUE TITLE
auth_url returns client_id as None

### ISSUE THREAD

**Issue by tino097** [marcospereirampj/python-keycloak#398]
Version 2.6.1 

Im using the lib to get the auth url but it returns the url with the `client_id` as None

Creating client with:
```
return KeycloakOpenID(
        server_url=server_url, client_id=client_id, realm_name=realm_name
    )
``` 
Using the client to retrieve the auth_url 
```
def get_auth_url(client, redirect_uri):
    return client.auth_url(redirect_uri=redirect_uri)
```
The url returned is `protocol/openid-connect/auth?client_id=None&response_type=code&redirect_uri=http://localhost:5000/user/sso_login/`

Am I missing someting or there is a bug with the `auth_url` method ?

**Comment by ryshoooo** [comment]
Nothing obvious, we have a unit test for this functionality which is not failing (https://github.com/marcospereirampj/python-keycloak/blob/aca13dec9a7fadaea39f686304120cb648e84ad0/tests/test_keycloak_openid.py#L110).

What is the python-keycloak version you are running?

**Comment by tino097** [comment]
@ryshoooo may bad sorry
one of my other requirements have installed older vesion and i was expeting that was 2.6.1 used
