### ISSUE TITLE
Add option to authenticate admin via access token

### ISSUE THREAD

**Issue by JeronimoMendes** [marcospereirampj/python-keycloak#404]
Currently the way to authenticate an admin is by providing `username` and `password`. I suggest adding an option to authenticate the user using an access token. Something like the following:
```python
from keycloak import KeycloakAdmin

keycloak_admin = KeycloakAdmin(server_url="http://localhost:8080/auth/",
                               access_token='admin-access-token',
                               realm_name="master",
                               user_realm_name="only_if_other_realm_than_master",
                               client_secret_key="client-secret",
                               verify=True)

```

It seems that `KeycloakAdmin.__init__()` is fetching an access token. I think we can skip that step if we already got the token.
There are even scenarios where an admin user would not be able to be authenticated currently, for example, if the only way to login was via an external IDP. In those cases we only got the access token.

I can work on this feature if it gets a green flag.

**Comment by jreusch** [comment]
wow, what a coincidence :D last week i exactly also needed that feature.
currently i'm "solving" it temporarily via passing custom_headers but in the end i'd suggest it exactly like you.
already have a version running with passing an initial token, but fighting with getting the testenv to work.

**Comment by jreusch** [comment]
to be more precise: i'd not recommend to only pass an access_token but also a refresh_token, or directly a dict than you can choose. this would allow to e.g. also use clients which only have authorization grant enabled.
