### ISSUE TITLE
Failed to recieve userinfo

### ISSUE THREAD

**Issue by areyeslo** [marcospereirampj/python-keycloak#410]
python-keycloak==0.24.0

from keycloak import KeycloakOpenID

keycloak_openid = KeycloakOpenID(server_url=server_url,
                                             client_id=client_id,
                                             realm_name=realm_name)

The previous configuration used to work in **RedHat keycloak 9.0.17**. However, I had to migrate to **RedHat Keycloak 18.0.3** and now I am getting the following **error: Failed to recieve userinfo**. I am able to confirm a valid response upon sending a GET request <host>/auth/realms/<realm name>/protocol/openid-connect/userinfo

I noticed the last version of python-keycloak library is 2.11.1. However, when installing the library, I am getting the following:
ERROR: Could not find a version that satisfies the requirement python-keycloak==2.11.1 (from versions: 0.2.0, 0.3.1, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.6.2, 0.6.4, 0.6.5, 0.7.0, 0.8.0, 0.8.2, 0.8.4, 0.9.0, 0.10.2, 0.11.0, 0.11.1, 0.12.0, 0.13.1, 0.13.2, 0.13.3, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.17.5, 0.17.6, 0.18.0, 0.19.0, 0.20.0, 0.21.0, 0.22.0, 0.23.0, 0.24.0, 0.25.0, 0.26.1, 0.27.0, 0.27.1)
ERROR: No matching distribution found for **python-keycloak==2.11.1**

Python is 3.6 taken from docker **python:3.6**

**Comment by ryshoooo** [comment]
Hi @areyeslo 

The `python-keycloak` library supports only [Python >= 3.7](https://github.com/marcospereirampj/python-keycloak/blob/master/pyproject.toml#L32). Our aim is to always be compatible with the latest version of Keycloak, there is pretty much no guarantee for older versions of Keycloak and older versions of this library. So the only guarantee we try to accommodate is that the latest python-keycloak library should always be compatible with the latest keycloak version.

I'm still trying to figure out what works/doesn't work in each version of Keycloak (https://github.com/marcospereirampj/python-keycloak/issues/319), I guess it could be expanded into each version of python-keycloak library, but then it easily becomes an unfeasible waste of time.

So my suggestion is, upgrade, upgrade, upgrade (upgrade python, upgrade keycloak, upgrade python-keycloak).
