### ISSUE TITLE
keycloak_openid attribute not set in KeycloakOpenIDConnection

### ISSUE THREAD

**Issue by mklassen** [marcospereirampj/python-keycloak#431]
If the `token` argument is passed during the initialization of a `KeycloakOpenIDConnection` instance, then the `get_token()` method is not called. However when the `refresh_token()` is subsequently called it attempts to access the `self.keycloak_openid` attribute which is set in `get_token()`. This results in the following error:

```
AttributeError: 'KeycloakOpenIDConnection' object has no attribute 'keycloak_openid'
```

The `keycloak_openid` should be an `@property` that creates the required `KeycloakOpenID` as required by either the `get_token()` or `refresh_token()` methods. It could also be an `@cached_property` to automatically handle the caching.

**Comment by mukarif** [comment]
same error my project.
_Error: cannot import name 'KeycloakOpenIDConnection' from 'keycloak'_
