### ISSUE TITLE
KeycloakOpenIDConnection: missing 1 indent 'server_url'

### ISSUE THREAD

**Issue by rserrano73** [marcospereirampj/python-keycloak#432]
`from keycloak import KeycloakAdmin
from keycloak import KeycloakOpenIDConnection

keycloak_connection = KeycloakOpenIDConnection(
                        server_url="http://localhost:8080/",
                        username='example-admin',
                        password='secret',
                        realm_name="master",
                        user_realm_name="only_if_other_realm_than_master",
                        client_id="my_client",
                        client_secret_key="client-secret",
                        verify=True)

keycloak_admin = KeycloakAdmin(connection=keycloak_connection)`
using my data, it worked once, then

Error message: __init__() missing 1 required positional argument: 'server_url'

I don't know why this error occurs

**Comment by Sonesson** [comment]
@rserrano73 
Try this:

`keycloak_admin = KeycloakAdmin("http://localhost:8080/", connection=keycloak_connection)`

**Comment by rserrano73** [comment]
I solved with this solution

from keycloak import KeycloakAdmin, KeycloakOpenIDConnection, KeycloakOpenID
    keycloak_openid = KeycloakOpenID(server_url="http://localhost:8080/",
                                 client_id=my_client_api_id,
                                 realm_name=my_realm,
                                 client_secret_key=my_client_api_secret_key)
    keycloak_admin = KeycloakAdmin(server_url="http://localhost:8080/",
                                username=admin_username,
                                password=admin_password,
                                realm_name="master",
                                user_realm_name=my_realm,
                                client_id=my_client_api_id,
                                client_secret_key=my_client_api_key,
                                verify=False)
