### ISSUE TITLE
Creating a client in a newly created realm?

### ISSUE THREAD

**Issue by bclements** [marcospereirampj/python-keycloak#437]
Hi,

I've created a realm using keycloak admin but I"m lost on how to create a client in that newly created realm. It tries to create a client in the master realm which is what the original keycloak admin connection contains.

Any help would be appreciated.

**Comment by lcdunne** [comment]
Hi @bclements - Just use `keycloak_admin.connection.realm_name = 'other-realm-name'`.

**Comment by ryshoooo** [comment]
Now there are helper methods called `get_current_realm` and `change_current_realm` in the admin client to identify and change realms.
