### ISSUE TITLE
Creating subgroups results in raised exception for 204 No Content

### ISSUE THREAD

**Issue by kereis** [marcospereirampj/python-keycloak#475]
When using `KeycloakAdmin.create_group()` with a set `parent=` parameter in order to create subgroups, the method raises an exception even if the operation is successful. This is because the API returns HTTP status code `204 No content`, which `KeycloakAdmin` does not expect.

https://github.com/marcospereirampj/python-keycloak/blob/5957607ad07536b94d878c3ce5d403c212b35220/src/keycloak/keycloak_admin.py#L1347-L1349

You'd probably just have to add 204 to `expected_codes` in order to fix that issue. I can create a PR if that fixes the issue.

**Comment by ryshoooo** [comment]
Hi @kereis 

Are you sure this is the issue you're facing? We have tests that create subgroups (https://github.com/marcospereirampj/python-keycloak/blob/78a0aa16b92d3a595cad962c1811f5c0fa4cc173/tests/test_keycloak_admin.py#L760) and these tests are not failing with any of the supported Keycloak versions (https://github.com/marcospereirampj/python-keycloak/actions).

**Comment by kereis** [comment]
Hi @ryshoooo,

unfortunately, I cannot remember anymore as it was 1 year ago and things may have changed until then. Sorry. 😅 

You can close this issue.
