### ISSUE TITLE
Docstrings point to an invalid URL

### ISSUE THREAD

**Issue by mjarosie** [marcospereirampj/python-keycloak#484]
All URLs pointing to Keycloak Rest API documentation are broken. [Here](https://github.com/marcospereirampj/python-keycloak/blob/5957607ad07536b94d878c3ce5d403c212b35220/src/keycloak/keycloak_admin.py#L523) is one of many examples:

https://www.keycloak.org/docs-api/18.0/rest-api/index.html#_realmrepresentation

returns a 404:

<img width="647" alt="image" src="https://github.com/marcospereirampj/python-keycloak/assets/9082353/5df3b18e-5e06-4913-960b-a68418b89c6d">

According to [this page](https://www.keycloak.org/documentation-archive.html) the oldest available API version that has a documentation at the moment is 21.0:

<img width="706" alt="image" src="https://github.com/marcospereirampj/python-keycloak/assets/9082353/6163156a-3dab-494e-bf08-16ed13962aea">

All comments would have to be updated to the latest version of Keycloak supported by this package (is that defined somewhere?), so for example if the latest supported Keycloak version is `22.0.3`, https://www.keycloak.org/docs-api/18.0/rest-api/index.html#_realmrepresentation would have to change to https://www.keycloak.org/docs-api/22.0.3/rest-api/index.html#RealmRepresentation

I did search for number of occurrences of `https://www.keycloak.org/docs-api/18.0`, there's around 100 of those in this repo.

**Comment by krisfremen** [comment]
@mjarosie have you started any work on this? I'd be up for taking it up if you haven't.

**Comment by mjarosie** [comment]
> @mjarosie have you started any work on this? I'd be up for taking it up if you haven't.

No I didn't work on that. Feel free to pick it up @krisfremen

**Comment by ryshoooo** [comment]
Should be fixed with the latest version
