### ISSUE TITLE
No module named 'keycloak_client'

### ISSUE THREAD

**Issue by UralmashFox** [marcospereirampj/python-keycloak#487]
I installed package with **pip install python-keycloak**
When trying to call **from keycloak_client import KeycloakOpenID** I get an error _ModuleNotFoundError: No module named 'keycloak_client'_

**Comment by carobme** [comment]
The package is named `keycloak`, not `keycloak_client`:

```python3
from keycloak import KeycloakOpenID
```

**Comment by ahmedsmaali5** [comment]
As @carobme mentioned you should use 
`from keycloak`
