### ISSUE TITLE
KeycloakAdmin can't connect to realm

### ISSUE THREAD

**Issue by marcospereirampj** [marcospereirampj/python-keycloak#5]
Connecting to the master realm work:

k=KeycloakAdmin(server_url="http://keycloak.dev.local:9000/auth/",username='admin',password='Pa55w0rd',verify=False)
But can't connect to a specific realm:
k=KeycloakAdmin(server_url="http://keycloak.dev.local:9000/auth/",username='admin',password='Pa55w0rd',verify=False, realm_name="myrealm")

return

keycloak.exceptions.KeycloakAuthenticationError: 401: b'{"error":"invalid_grant","error_description":"Invalid user credentials"}'

**Comment by laktak** [comment]
You need to connect to the master realm first and then set

`k.realm_name = "myrealm"`
