### ISSUE TITLE
grant_type bug in keycloak_admin.py

### ISSUE THREAD

**Issue by rabihsaliba** [marcospereirampj/python-keycloak#51]
The following lines (1166 and 1167) in keycloak_admin.py:
`        if self.client_secret_key:
            grant_type = ["client_credentials"]` 

will cause an error when using a confidential client by forcing the client to obtain an access token outside of the context of the admin user (which is what a client_credentials grant type does)

**Comment by double-a** [comment]
AFAIK the grant_type is correct when using a confidential client (https://www.keycloak.org/docs/latest/server_admin/#_service_accounts).
Using the client_id and client_secret_key (no username, no password) I can create the KeycloakAdmin without problems.
Which parameters do you use?
