### ISSUE TITLE
Auto refresh does not work in case of stale refresh token

### ISSUE THREAD

**Issue by gt-novelt** [marcospereirampj/python-keycloak#53]
Steps to reproduce:

1. Instantiate KeycloakAdmin with refresh token

1. Login in the keycloak administration console

1. Use the previously instantiated KeycloakAdmin

You should get an error:
> 400: b'{\"error\":\"invalid_grant\",\"error_description\":\"Stale refresh token\"}'

The issue is within the refresh_token method. It only checks for expired token, not stale tokens:
https://github.com/marcospereirampj/python-keycloak/blob/57e8bc138290aa4bc3af55760e9009dd0ce71ef4/keycloak/keycloak_admin.py#L1190

**Comment by domsie** [comment]
is there a workaround for this behaviour @gt-novelt ?

**Comment by gt-novelt** [comment]
I suppose replacing the if statement by this would work:
```python
if e.response_code == 400 and (b'Refresh token expired' in e.response_body or b'Stale refresh token' in e.response_body): 
[...]
```

I have not tested it though.

**Comment by domsie** [comment]
looks fine the code change; but i cant test using an customised python-keycloak version and must therefore wait for an official change / new version. Did you test an workaround in your client implementation as well or did you have a proper idea to fix that issue temporarily on client side?

**Comment by gt-novelt** [comment]
I am using the unfixed version and had not encountered the issue so far.

To be honest I had forgotten about this one...

**Comment by gt-novelt** [comment]
closing:
https://github.com/marcospereirampj/python-keycloak/blob/859ea999481213cf6adf7718e56b44ee599c371a/keycloak/keycloak_admin.py#L2316-L2320
