### ISSUE TITLE
Creating user return empty bytes

### ISSUE THREAD

**Issue by hariyerramsetty** [marcospereirampj/python-keycloak#60]
Hey guys, 

I don't know if this is the issue with library or my keycloak setup. But when I am doing keycloak-admin.createuser(userrepresentation). I am getting null empty byte string.

![Screen Shot 2020-02-16 at 3 51 14 AM](https://user-images.githubusercontent.com/2007206/74601793-e8782000-506f-11ea-8ff6-d124ba5df236.png)

The first one was creating a existing user. I agree that it returns right id but creating new user is returning empty byte string. Am I missing anything?

**Comment by marcospereirampj** [comment]
It is the default answer for Keycloak, but in the next release, we changed it to return the user id created.

See this [PR-31](https://github.com/marcospereirampj/python-keycloak/pull/31).
