### ISSUE TITLE
missing dependency dataclasses

### ISSUE THREAD

**Issue by RubenGarcia** [marcospereirampj/python-keycloak#62]
On a Ubuntu 18.04.3 LTS with no previous installation of python keycloak
----------------
$ python3 -m pip install keycloak
Collecting keycloak
  Downloading https://files.pythonhosted.org/packages/c9/e9/34f64356eb46972cbfde2ac1f7347d05faec74c990877d0e8b783a47f007/keycloak-2.0.0-py3-none-any.whl
Collecting cached-property (from keycloak)
  Downloading https://files.pythonhosted.org/packages/3b/86/85c1be2e8db9e13ef9a350aecd6dea292bd612fa288c2f40d035bb750ded/cached_property-1.5.1-py2.py3-none-any.whl
Collecting pyyaml (from keycloak)
  Downloading https://files.pythonhosted.org/packages/3d/d9/ea9816aea31beeadccd03f1f8b625ecf8f645bd66744484d162d84803ce5/PyYAML-5.3.tar.gz (268kB)
    100% |████████████████████████████████| 276kB 2.3MB/s 
Collecting cryptography (from keycloak)
  Downloading https://files.pythonhosted.org/packages/45/73/d18a8884de8bffdcda475728008b5b13be7fbef40a2acc81a0d5d524175d/cryptography-2.8-cp34-abi3-manylinux1_x86_64.whl (2.3MB)
    100% |████████████████████████████████| 2.3MB 609kB/s 
Collecting requests (from keycloak)
  Downloading https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 10.4MB/s 
Collecting pyjwt (from keycloak)
  Downloading https://files.pythonhosted.org/packages/87/8b/6a9f14b5f781697e51259d81657e6048fd31a113229cf346880bb7545565/PyJWT-1.7.1-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography->keycloak)
  Downloading https://files.pythonhosted.org/packages/f1/c7/72abda280893609e1ddfff90f8064568bd8bcb2c1770a9d5bb5edb2d1fea/cffi-1.14.0-cp36-cp36m-manylinux1_x86_64.whl (399kB)
    100% |████████████████████████████████| 399kB 3.9MB/s 
Collecting six>=1.4.1 (from cryptography->keycloak)
  Downloading https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting idna<3,>=2.5 (from requests->keycloak)
  Downloading https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 13.1MB/s 
Collecting certifi>=2017.4.17 (from requests->keycloak)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl (156kB)
    100% |████████████████████████████████| 163kB 813kB/s 
Collecting chardet<4,>=3.0.2 (from requests->keycloak)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 5.9MB/s 
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->keycloak)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl (125kB)
    100% |████████████████████████████████| 133kB 10.9MB/s 
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography->keycloak)
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
    100% |████████████████████████████████| 163kB 6.0MB/s 
Building wheels for collected packages: pyyaml, pycparser
  Running setup.py bdist_wheel for pyyaml ... done
  Stored in directory: /home/rgarcia/.cache/pip/wheels/e4/76/4d/a95b8dd7b452b69e8ed4f68b69e1b55e12c9c9624dd962b191
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /home/rgarcia/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
Successfully built pyyaml pycparser
Installing collected packages: cached-property, pyyaml, pycparser, cffi, six, cryptography, idna, certifi, chardet, urllib3, requests, pyjwt, keycloak
Successfully installed cached-property-1.5.1 certifi-2019.11.28 cffi-1.14.0 chardet-3.0.4 cryptography-2.8 idna-2.9 keycloak-2.0.0 pycparser-2.19 pyjwt-1.7.1 pyyaml-5.3 requests-2.23.0 six-1.14.0 urllib3-1.25.8
--------------------
$ cat > tests.py
from keycloak import KeycloakOpenID
^D
----------------
$ python3 tests.py
Traceback (most recent call last):
  File "tests.py", line 1, in <module>
    from keycloak import KeycloakOpenID
  File "/home/rgarcia/.local/lib/python3.6/site-packages/keycloak/__init__.py", line 7, in <module>
    from .mixins.authentication import AuthenticationMixin
  File "/home/rgarcia/.local/lib/python3.6/site-packages/keycloak/mixins/authentication.py", line 9, in <module>
    from ..config import config
  File "/home/rgarcia/.local/lib/python3.6/site-packages/keycloak/config.py", line 6, in <module>
    from dataclasses import dataclass, fields
ModuleNotFoundError: No module named 'dataclasses'

**Comment by RubenGarcia** [comment]
After installing dependency, I get a different error:
$ python3 -m pip install dataclasses
Collecting dataclasses
  Downloading https://files.pythonhosted.org/packages/e1/d2/6f02df2616fd4016075f60157c7a0452b38d8f7938ae94343911e0fb0b09/dataclasses-0.7-py3-none-any.whl
Installing collected packages: dataclasses
Successfully installed dataclasses-0.7
rgarcia@ubuntu:~/irods-ansible-latest/scripts/generic$ python3 tests.py 
Traceback (most recent call last):
  File "tests.py", line 1, in <module>
    from keycloak import KeycloakOpenID
ImportError: cannot import name 'KeycloakOpenID'

**Comment by marcospereirampj** [comment]
Keycloak is another library.

[Link to Keycloak.](https://libraries.io/pypi/keycloak/2.0.1)
