### ISSUE TITLE
Old httpx version

### ISSUE THREAD

**Issue by mootfrost** [marcospereirampj/python-keycloak#620]
Devs of httpx renamed `proxies` field to `proxy`  in `httpx.AsyncClient`. Now its impossible to use library alongside with packages that require newer version and also set this parameter.

**Comment by jonmongeau13** [comment]
https://github.com/marcospereirampj/python-keycloak/compare/master...jonmongeau13:python-keycloak:patch-1 I have this brewing but I really not comfortable with the PR process for open source projects like this. If someone else is familiar with the project, this is along the lines of the fix.

**Comment by jonmongeau13** [comment]
PR: https://github.com/marcospereirampj/python-keycloak/pull/621

**Comment by jonthemango** [comment]
PR: https://github.com/marcospereirampj/python-keycloak/pull/622

**Comment by jonmongeau13** [comment]
Since `proxy` is meant for strings and current implementation expects dicts, `mounts` is the correct replacement for `proxies`.

**Comment by jonthemango** [comment]
Since `proxies` in keycloak accepts `dict` as the type. The correct replacement is `mounts`, not `proxy`. `proxy` is for string-like values.

https://www.python-httpx.org/advanced/proxies/

**Comment by jonmongeau13** [comment]
Merged, issue can be closed I think.
