### ISSUE TITLE
0.19.0 Release is broken because of changes to raw delete

### ISSUE THREAD

**Issue by lemccarthy** [marcospereirampj/python-keycloak#65]
Problem commit: https://github.com/marcospereirampj/python-keycloak/pull/56

Every instance of raw delete in KeycloakAdmin where the data parameter is not explicitly passed to `raw_delete` is now broken thanks to this change. There are 5 methods that are broken as a result of this commit:

`delete_client_role`
`delete_user`
`group_user_remove`
`delete_group`
`delete_client`

Calling any of them will get you this error message:

```
TypeError: raw_delete() missing 1 required positional argument: 'data'
```

@gitfrosh 

This can be fixed simply by making data an optional argument instead of a required one.

**Comment by paoloromolini** [comment]
Yes I confirm the same problem

**Comment by zwurv** [comment]
Here's my temporary solution until next version:

    def _delete_user(self, user_id: str):
        """
        This method is a temporary thing due to bug
        https://github.com/marcospereirampj/python-keycloak/issues/65
        :param user_id:
        :return:
        """
        params_path = {"realm-name": KEYCLOAK_REALM_NAME, "id": user_id}
        data_raw = self.admin.raw_delete("admin/realms/{realm-name}/users/{id}".format(**params_path), data={})
        from keycloak.exceptions import raise_error_from_response, KeycloakGetError
        return raise_error_from_response(data_raw, KeycloakGetError, expected_code=204)
