### ISSUE TITLE
How can you assign roles to a group

### ISSUE THREAD

**Issue by yangzinan** [marcospereirampj/python-keycloak#72]
I want to assign roles to a group. How can I do this?

**Comment by yangzinan** [comment]
I want to assign client roles to a group

**Comment by paoloromolini** [comment]
With the new release now you can:
https://github.com/marcospereirampj/python-keycloak/pull/64/files

**Comment by Allan-Nava** [comment]
> With the new release now you can:
> https://github.com/marcospereirampj/python-keycloak/pull/64/files

+1
