### ISSUE TITLE
Bug: Cannot delete user using KeycloakAdmin.delete_user

### ISSUE THREAD

**Issue by EmilioEduardo** [marcospereirampj/python-keycloak#74]
When using function delete_user from keycloak_admin (keycloak_admin.py::382), no data parameter is provided to raw_delete, which leads to a runtime error.

Please, change keycloak_admin.py::382 line to:

data_raw = self.raw_delete(URL_ADMIN_USER.format(**params_path), data = dict())

This will fix the problem.

Best regards

**Comment by ghost** [comment]
The same issue is apparent when executing group_user_remove(user_id=<>, group_id=<>)

The above also fixes this issue.

**Comment by fr33mang** [comment]
Hi!
Same error with delete_user method.
Can I create PR for this issue?
