### ISSUE TITLE
keycloak_openid.decode_token fails if user has client role assigned

### ISSUE THREAD

**Issue by marcospereirampj** [marcospereirampj/python-keycloak#8]
Hi, I'm facing the problem, that keycloak_openid.decode_token() fails to decode my token if I assign any client role to my user. Without any client role assigned, everything works fine, but if I assign e.g. "view-clients" or "realm-admin", decode fails with "Invalid audience".

here is the corresponding line of code:

token_info = keycloak_openid.decode_token(token, keycloak_openid.certs(),algorithms=['RS512'])

Debug info:
Exception: Invalid audience

**Comment by HalikovDj** [comment]
Hello I also encountered this problem could you explain how you fixed it?
