### ISSUE TITLE
send_update_account throws KeycloakException: 204: b'' with Keycloak 10

### ISSUE THREAD

**Issue by chmller** [marcospereirampj/python-keycloak#91]
Hi

i use send_update_account to let a user reset his/hers password.
My call looks like so: send_update_account(user_id, '["UPDATE_PASSWORD"]', client_id='MY_CLIENT_ID', redirect_uri='/whatever').

However, since i updated to Keycloak 10.0.1, the underlying HTTP-call returns with 204 instead of 200.
Which results in a KeycloakException.
I am pretty sure this wasnt a problem in Keycloak 9.

**Comment by Anton0** [comment]
I can confirm I'm seeing this as well using the `send_verify_email` function after moving from a pre-10 version to `10.0.2` - the call succeeds with a HTTP 204 response which then generates a KeycloakException

**Comment by hariyerramsetty** [comment]
Facing this issue with ```send_verify_email```. 

Keycloak Version:10.0.2

```
(Pdb) self.keycloak_admin.send_verify_email(self.keycloak_admin.get_user_id(kwargs['email']), self.client_id, redirect_uri=os.getenv('VERIFY_EMAIL_REDIRECT_URI'))
*** keycloak.exceptions.KeycloakGetError: 204: b''
(Pdb)
```
